CC = gcc
.PHONEY: all clean bruteForceStringMatch 

bruteForceStringMatch: bruteForceStringMatch.c
	$(CC) $< -o $@  
sequentialsearch:sequentialsearch.c
	$(CC) $< -o $@
bubblesort:bubblesort.c
	$(CC) $< -o $@
selectsort:selectsort.c
	$(CC) $< -o $@

clean:
	rm *.o 
