CC = gcc
.PHONEY: all clean
all: bruteForceStringMatch  bruteForceClosestPoints

bruteForceStringMatch: bruteForceStringMatch.c
	$(CC) $< -o $@  
sequentialsearch:sequentialsearch.c
	$(CC) $< -o $@
bubblesort:bubblesort.c
	$(CC) $< -o $@
selectsort:selectsort.c
	$(CC) $< -o $@
bruteForceClosestPoints:bruteForceClosestPoints.c
	$(CC) $< -o $@
clean:
	rm *.o 
